Repository THE-SOPT-30th-DaangnMarket-Team16-2/CarrotIsDelicious-AOS, pull requests merged in 2022-05, with the labels that each got.

#2 #1 [chore] 프로젝트 초기 세팅
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/carrot16_2/MainActivity.kt
  app/src/main/java/org/sopt/carrot16_2/ui/base/BaseActivity.kt
  app/src/main/java/org/sopt/carrot16_2/ui/base/BaseFragment.kt
  app/src/main/java/org/sopt/carrot16_2/ui/create/CreateActivity.kt
  app/src/main/java/org/sopt/carrot16_2/ui/main/HomeActivity.kt
  app/src/main/java/org/sopt/carrot16_2/ui/read/ReadActivity.kt
  app/src/main/java/org/sopt/carrot16_2/util/BindingAdapters.kt
  app/src/main/res/layout/activity_create.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_read.xml
Labels: pull request, 재훈

#4 #2 [chore] 글꼴, 색상 추가
  app/src/main/res/font/roboto.xml
  app/src/main/res/font/roboto_bold.ttf
  app/src/main/res/font/roboto_medium.ttf
  app/src/main/res/font/roboto_regular.ttf
  app/src/main/res/font/roboto_semi_bold.ttf
  app/src/main/res/values/colors.xml
Labels: pull request, 재훈

#6 #5 [layout] activity_create 구성
  .idea/.name
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/res/drawable/ic_and__icon__camera.xml
  app/src/main/res/drawable/ic_and_btn_back2.xml
  app/src/main/res/drawable/ic_and_btn_checkkk.xml
  app/src/main/res/drawable/ic_and_btn_finishxxx.xml
  app/src/main/res/drawable/ic_and_icon_range.xml
  app/src/main/res/drawable/ic_and_icon_smile.xml
  app/src/main/res/drawable/ic_and_icon_word.xml
  app/src/main/res/drawable/ic_and_lowmenu.xml
  app/src/main/res/drawable/ic_line_3.xml
  app/src/main/res/drawable/ic_rectangle_6.xml
  app/src/main/res/layout/activity_create.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: pull request, 현정

#9 #8 [modify] activity_create 수정
  .idea/misc.xml
  app/src/main/res/drawable/ic_check_on.xml
  app/src/main/res/drawable/selector_radio.xml
  app/src/main/res/layout/activity_create.xml
  app/src/main/res/values/strings.xml
Labels: pull request, 현정

#10 #7 [layout] item_image_list layout 구성
  .idea/misc.xml
  app/src/main/java/org/sopt/carrot16_2/model/ImageData.kt
  app/src/main/res/drawable-v24/bookimage1.9.png
  app/src/main/res/drawable/ic_and_icon_x.xml
  app/src/main/res/layout/activity_create.xml
  app/src/main/res/layout/item_image_list.xml
Labels: pull request, 현정

#15 #12 [layout] Read 뷰 구성 완료
  .idea/gradle.xml
  app/src/main/res/drawable/ic_alarm_btn.xml
  app/src/main/res/drawable/ic_arrow_down.xml
  app/src/main/res/drawable/ic_back_btn.xml
  app/src/main/res/drawable/ic_cate_btn.xml
  app/src/main/res/drawable/ic_chat.xml
  app/src/main/res/drawable/ic_chat_fill.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_check_fill.xml
  app/src/main/res/drawable/ic_heart.xml
  app/src/main/res/drawable/ic_heart_fill.xml
  app/src/main/res/drawable/ic_home_btn.xml
  app/src/main/res/drawable/ic_home_fill.xml
  app/src/main/res/drawable/ic_manner_bar.xml
  app/src/main/res/drawable/ic_manner_smile.xml
  app/src/main/res/drawable/ic_menu_btn.xml
  app/src/main/res/drawable/ic_my.xml
  app/src/main/res/drawable/ic_my_fill.xml
  app/src/main/res/drawable/ic_myplace.xml
  app/src/main/res/drawable/ic_myplace_fill.xml
  app/src/main/res/drawable/ic_share_btn.xml
  app/src/main/res/drawable/ic_town.xml
  app/src/main/res/drawable/ic_town_fill.xml
  app/src/main/res/drawable/shape_read_chat_list_btn.xml
  app/src/main/res/drawable/shape_read_state_btn.xml
  app/src/main/res/layout/activity_read.xml
  app/src/main/res/values/strings.xml
Labels: pull request, 재훈

#17 #16 [layout] 홈 뷰 사전 작업
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/ic_address_btn.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_search_btn.xml
  app/src/main/res/drawable/ic_write_btn.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/menu/menu_home.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: refactor, 재훈

#19 #18 [layout] 홈 뷰 바텀네비게이션 설정 완료
  app/src/main/res/drawable/selector_home_bnv_chat.xml
  app/src/main/res/drawable/selector_home_bnv_home.xml
  app/src/main/res/drawable/selector_home_bnv_my.xml
  app/src/main/res/drawable/selector_home_bnv_myplace.xml
  app/src/main/res/drawable/selector_home_bnv_town.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/menu/menu_home.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: layout, 재훈

#21 #20 [feat] Read Activity 뷰 페이저 설정 및 액티비티 연결 완료
  .idea/gradle.xml
  app/src/main/java/org/sopt/carrot16_2/ui/create/CreateActivity.kt
  app/src/main/java/org/sopt/carrot16_2/ui/main/HomeActivity.kt
  app/src/main/java/org/sopt/carrot16_2/ui/read/ReadActivity.kt
  app/src/main/java/org/sopt/carrot16_2/ui/read/StateBottomSheet.kt
  app/src/main/java/org/sopt/carrot16_2/ui/read/adapter/ReadViewPagerAdapter.kt
  app/src/main/res/drawable/ic_indicator_selected.xml
  app/src/main/res/drawable/ic_indicator_unselected.xml
  app/src/main/res/drawable/selector_read_indicator.xml
  app/src/main/res/layout/activity_read.xml
  app/src/main/res/layout/bottom_sheet_state.xml
  app/src/main/res/layout/item_read_vp_item.xml
  app/src/main/res/values/strings.xml
Labels: pull request, 재훈

#25 #23 [fix] 뷰페이저 인디케이터 수정 완료
  app/build.gradle
  app/src/main/java/org/sopt/carrot16_2/ui/read/ReadActivity.kt
  app/src/main/res/layout/activity_read.xml
Labels: 재훈

#28 #26 [서버] 서버 API 구현 사전 작업
  app/build.gradle
  app/src/main/java/org/sopt/carrot16_2/data/remote/RetrofitBuilder.kt
  app/src/main/java/org/sopt/carrot16_2/ui/base/BaseActivity.kt
  app/src/main/java/org/sopt/carrot16_2/ui/base/BaseFragment.kt
  app/src/main/java/org/sopt/carrot16_2/ui/create/CreateActivity.kt
  app/src/main/java/org/sopt/carrot16_2/ui/create/viewmodel/CreateViewModel.kt
  app/src/main/java/org/sopt/carrot16_2/ui/main/HomeActivity.kt
  app/src/main/java/org/sopt/carrot16_2/ui/main/viewmodel/HomeViewModel.kt
  app/src/main/java/org/sopt/carrot16_2/ui/read/ReadActivity.kt
  app/src/main/java/org/sopt/carrot16_2/ui/read/viewmodel/ReadViewModel.kt
  app/src/main/res/layout/activity_create.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_read.xml
Labels: pull request, 재훈

#31 #29 [Read] 뷰모델 적용 및 서버 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/carrot16_2/data/remote/RetrofitBuilder.kt
  app/src/main/java/org/sopt/carrot16_2/data/remote/entity/response/BaseResponse.kt
  app/src/main/java/org/sopt/carrot16_2/data/remote/entity/response/ReadResponse.kt
  app/src/main/java/org/sopt/carrot16_2/data/remote/service/ReadService.kt
  app/src/main/java/org/sopt/carrot16_2/ui/read/ReadActivity.kt
  app/src/main/java/org/sopt/carrot16_2/ui/read/StateBottomSheet.kt
  app/src/main/java/org/sopt/carrot16_2/ui/read/viewmodel/ReadViewModel.kt
  app/src/main/java/org/sopt/carrot16_2/util/BindingAdapters.kt
  app/src/main/res/layout/activity_read.xml
  app/src/main/res/values/strings.xml
Labels: pull request, 재훈

#30 #24 [refactor] viewModel 수정
  app/src/main/java/org/sopt/carrot16_2/ui/create/CreateActivity.kt
  app/src/main/java/org/sopt/carrot16_2/ui/create/viewmodel/CreateViewModel.kt
  app/src/main/java/org/sopt/carrot16_2/viewModel/CreateViewModel.kt
Labels: pull request, 현정
